[package]
name = "xform_to_xml"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = "0.31"  # good for generating XML from Rust
wasm-bindgen = "0.2"

