[package]
name = "xformify-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
# cdylib is required for wasm-bindgen
crate-type = ["cdylib"]

[dependencies]
xformify-core = { path = "../xformify-core" }
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
# Optional but recommended for nicer panics in the browser:
console_error_panic_hook = { version = "0.1", optional = true }

[features]
default = []
panic-hook = ["console_error_panic_hook"]
