// This file was initially generated by ChatGPT on the 6th of June 2025.

export type ITextMap = {
    [key: string]: Record<string, string>;
}[];

export const extractITextTranslations = (xmlString: string): ITextMap => {
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlString, "text/xml");

    const translations = xmlDoc.querySelectorAll("translation");

    const result: { [key: string]: Record<string, string> }[] = []; // corrected syntax

    translations.forEach((translation) => {
        const lang = translation.getAttribute("lang") ?? "";

        const texts = translation.querySelectorAll("text");

        texts.forEach((textEl) => {
            const id = textEl.getAttribute("id") ?? "";
            const valueEl = textEl.querySelector("value");
            const value = valueEl ? valueEl.textContent?.trim() ?? "" : "";

            result.push({
                [id]: { lang, value }, // updated to match new structure
            });
        });
    });

    return result;
}