[package]
name = "xformify-core"
version = "0.1.0"
edition = "2021"

[lib]
# rlib is fine for Rust usage AND as a dependency of the wasm wrapper
crate-type = ["rlib"]
path = "src/lib.rs"

[dependencies]
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
quick-xml = { version = "0.36", features = ["serialize"] }
regex = "1"
once_cell = "1.18"